export const items = [
  {
    Item: "Air Conditioner 1' x 1'",
    dimensions: 5,
    weight: 35,
    costPer: 40,
    icon: "AcUnit",
  },
  {
    Item: "Air Conditioner 1.5' x 1.5' x 4'",
    dimensions: 8,
    weight: 56,
    costPer: 60,
    icon: "AcUnit",
  },
  {
    Item: "Air Conditioner 2' x 2' x 4'",
    dimensions: 10,
    weight: 70,
    costPer: 75,
    icon: "AcUnit",
  },
  {
    Item: "Air Conditioner - Window",
    dimensions: 15,
    weight: 105,
    costPer: 110,
    icon: "AcUnit",
  },
  {
    Item: "Air Fryer",
    dimensions: 2,
    weight: 14,
    costPer: 18,
    icon: "Kitchen",
  },
  { Item: "Air Purifier", dimensions: 3, weight: 21, costPer: 25, icon: "Air" },
  {
    Item: "Arm Chair",
    dimensions: 12,
    weight: 84,
    costPer: 90,
    icon: "Weekend",
  },
  {
    Item: "Armoire 3' x 7'",
    dimensions: 40,
    weight: 280,
    costPer: 300,
    icon: "BedroomBaby",
  },
  {
    Item: "Armoire 4' x 8'",
    dimensions: 60,
    weight: 420,
    costPer: 450,
    icon: "BedroomBaby",
  },
  {
    Item: "Baby Carriage",
    dimensions: 4,
    weight: 28,
    costPer: 35,
    icon: "BabyCarriage",
  },
  {
    Item: "Baby Grand Piano",
    dimensions: 80,
    weight: 560,
    costPer: 600,
    icon: "Piano",
  },
  {
    Item: "Baby Stroller",
    dimensions: 4,
    weight: 28,
    costPer: 32,
    icon: "Stroller",
  },
  {
    Item: "Bakers Rack",
    dimensions: 40,
    weight: 280,
    costPer: 290,
    icon: "BakeryDining",
  },
  {
    Item: "Bar - Portable",
    dimensions: 15,
    weight: 105,
    costPer: 120,
    icon: "Liquor",
  },
  { Item: "Bar Stool", dimensions: 6, weight: 42, costPer: 48, icon: "Chair" },
  {
    Item: "Basket",
    dimensions: 5,
    weight: 35,
    costPer: 38,
    icon: "ShoppingBasket",
  },
  { Item: "Bassinet", dimensions: 10, weight: 70, costPer: 77, icon: "Crib" },
  {
    Item: "Bathroom Cabinet",
    dimensions: 10,
    weight: 70,
    costPer: 80,
    icon: "Bathroom",
  },
  { Item: "Bean Bag", dimensions: 7, weight: 49, costPer: 55, icon: "Weekend" },
  {
    Item: "Bed - Bunk (set of 2 beds)",
    dimensions: 70,
    weight: 490,
    costPer: 510,
    icon: "Bed",
  },
  {
    Item: "Bed - Cot / Rollaway / Folding",
    dimensions: 10,
    weight: 70,
    costPer: 85,
    icon: "Bed",
  },
  {
    Item: "Bed - Single / Twin (Frame, Box Spring and Mattress)",
    dimensions: 40,
    weight: 280,
    costPer: 295,
    icon: "Bed",
  },
  {
    Item: "Bed - Full / Double (Frame, Box Spring and Mattress)",
    dimensions: 60,
    weight: 420,
    costPer: 430,
    icon: "Bed",
  },
  {
    Item: "Bed - Queen (Frame, Box Spring and Mattress)",
    dimensions: 65,
    weight: 455,
    costPer: 470,
    icon: "Bed",
  },
  {
    Item: "Bed - King (Frame, Box Spring and Mattress)",
    dimensions: 70,
    weight: 490,
    costPer: 520,
    icon: "Bed",
  },
  {
    Item: "Bed - Youth",
    dimensions: 30,
    weight: 210,
    costPer: 220,
    icon: "ChildCare",
  },
  {
    Item: "Bed Frame - Folding Metal",
    dimensions: 15,
    weight: 105,
    costPer: 115,
    icon: "Bed",
  },
  {
    Item: "Bed Frame - Metal",
    dimensions: 20,
    weight: 140,
    costPer: 155,
    icon: "Bed",
  },
  {
    Item: "Bed Frame with Storage",
    dimensions: 25,
    weight: 175,
    costPer: 190,
    icon: "Bed",
  },
  { Item: "Bench", dimensions: 15, weight: 105, costPer: 120, icon: "Weekend" },
  {
    Item: "Bicycle (Bike)",
    dimensions: 10,
    weight: 70,
    costPer: 80,
    icon: "PedalBike",
  },
  {
    Item: "Bike Rack",
    dimensions: 2,
    weight: 14,
    costPer: 20,
    icon: "DirectionsBike",
  },
  { Item: "Blender", dimensions: 1, weight: 7, costPer: 10, icon: "Blender" },
  {
    Item: "Bookcase 3' x 3'",
    dimensions: 10,
    weight: 70,
    costPer: 85,
    icon: "MenuBook",
  },
  {
    Item: "Bookcase 4' x 6'",
    dimensions: 20,
    weight: 140,
    costPer: 160,
    icon: "MenuBook",
  },
  {
    Item: "Bookcase 4' x 8'",
    dimensions: 40,
    weight: 280,
    costPer: 300,
    icon: "MenuBook",
  },
  {
    Item: "Bookcase - Large",
    dimensions: 50,
    weight: 300,
    costPer: 320,
    icon: "MenuBook",
  },
  {
    Item: "Boudoir Chair",
    dimensions: 10,
    weight: 70,
    costPer: 80,
    icon: "Weekend",
  },
  {
    Item: "Bowling Ball and Bag",
    dimensions: 3,
    weight: 21,
    costPer: 28,
    icon: "SportsBowling",
  },
  {
    Item: "Box Spring - Single/ Twin",
    dimensions: 15,
    weight: 105,
    costPer: 115,
    icon: "Bed",
  },
  {
    Item: "Box Spring - Full/ Double",
    dimensions: 20,
    weight: 140,
    costPer: 160,
    icon: "Bed",
  },
  {
    Item: "Box Spring - Queen",
    dimensions: 25,
    weight: 175,
    costPer: 190,
    icon: "Bed",
  },
  {
    Item: "Box Spring - King",
    dimensions: 30,
    weight: 210,
    costPer: 230,
    icon: "Bed",
  },
  {
    Item: "Breakfast Table",
    dimensions: 10,
    weight: 70,
    costPer: 80,
    icon: "TableBar",
  },
  {
    Item: "Buffet",
    dimensions: 35,
    weight: 245,
    costPer: 260,
    icon: "Countertops",
  },
  {
    Item: "Buffet (Base)",
    dimensions: 30,
    weight: 210,
    costPer: 230,
    icon: "Countertops",
  },
  { Item: "Bunk Bed", dimensions: 110, weight: 770, costPer: 800, icon: "Bed" },
  {
    Item: "Bureau or Chest Of Drawers",
    dimensions: 25,
    weight: 175,
    costPer: 190,
    icon: "Inventory",
  },
  {
    Item: "Butcher Block",
    dimensions: 15,
    weight: 105,
    costPer: 120,
    icon: "Countertops",
  },
  {
    Item: "Cabinet - Curio",
    dimensions: 10,
    weight: 70,
    costPer: 85,
    icon: "Kitchen",
  },
  {
    Item: "Captain's Bed",
    dimensions: 40,
    weight: 280,
    costPer: 300,
    icon: "Bed",
  },
  {
    Item: "Car Seat",
    dimensions: 5,
    weight: 35,
    costPer: 42,
    icon: "AirlineSeatLegroomNormal",
  },
  {
    Item: "Card Table",
    dimensions: 8,
    weight: 56,
    costPer: 65,
    icon: "TableBar",
  },
  {
    Item: "Cat Litter Box (New)",
    dimensions: 5,
    weight: 35,
    costPer: 40,
    icon: "Pets",
  },
  {
    Item: "Cat Tower - Small",
    dimensions: 2,
    weight: 15,
    costPer: 20,
    icon: "Pets",
  },
  {
    Item: "Cat Tower - Medium",
    dimensions: 3,
    weight: 21,
    costPer: 28,
    icon: "Pets",
  },
  {
    Item: "Cat Tower - Large",
    dimensions: 6,
    weight: 42,
    costPer: 50,
    icon: "Pets",
  },
  {
    Item: "Cat Tree Medium",
    dimensions: 15,
    weight: 105,
    costPer: 120,
    icon: "Pets",
  },
  {
    Item: "Cat Tree Small",
    dimensions: 7,
    weight: 49,
    costPer: 60,
    icon: "Pets",
  },
  {
    Item: "CD Rack",
    dimensions: 7,
    weight: 49,
    costPer: 55,
    icon: "LibraryMusic",
  },
  {
    Item: "CD, DVD, VCR Player",
    dimensions: 3,
    weight: 21,
    costPer: 25,
    icon: "Dvr",
  },
  {
    Item: "Chaise Lounge",
    dimensions: 30,
    weight: 210,
    costPer: 230,
    icon: "Deck",
  },
  {
    Item: "Changing Table",
    dimensions: 15,
    weight: 105,
    costPer: 120,
    icon: "BabyChangingStation",
  },
  {
    Item: "Chest Freezer",
    dimensions: 26,
    weight: 182,
    costPer: 200,
    icon: "Kitchen",
  },
  {
    Item: "Children's Bed",
    dimensions: 20,
    weight: 140,
    costPer: 160,
    icon: "ChildCare",
  },
  {
    Item: "Children's Bicycle (Bike)",
    dimensions: 7,
    weight: 49,
    costPer: 60,
    icon: "PedalBike",
  },
  {
    Item: "Children's Chair",
    dimensions: 4,
    weight: 28,
    costPer: 35,
    icon: "Weekend",
  },
  {
    Item: "Children's Table",
    dimensions: 5,
    weight: 35,
    costPer: 42,
    icon: "TableBar",
  },
  {
    Item: "Child's / Kid's Table",
    dimensions: 5,
    weight: 35,
    costPer: 45,
    icon: "TableBar",
  },
  {
    Item: "China Cabinet 3' x 7' tall",
    dimensions: 30,
    weight: 210,
    costPer: 230,
    icon: "Kitchen",
  },
  {
    Item: "China Cabinet 3.5' x 7' tall",
    dimensions: 40,
    weight: 280,
    costPer: 310,
    icon: "Kitchen",
  },
  {
    Item: "China Cabinet 4' x 8' tall",
    dimensions: 50,
    weight: 350,
    costPer: 380,
    icon: "Kitchen",
  },
  {
    Item: "Clarinet",
    dimensions: 3,
    weight: 21,
    costPer: 30,
    icon: "MusicNote",
  },
  {
    Item: "Clothes Basket",
    dimensions: 5,
    weight: 35,
    costPer: 42,
    icon: "LocalLaundryService",
  },
  {
    Item: "Clothes Hamper",
    dimensions: 5,
    weight: 35,
    costPer: 45,
    icon: "LocalLaundryService",
  },
  {
    Item: "Clothing Rack",
    dimensions: 5,
    weight: 35,
    costPer: 50,
    icon: "Checkroom",
  },
  {
    Item: "Club Chair",
    dimensions: 20,
    weight: 140,
    costPer: 160,
    icon: "Weekend",
  },
  {
    Item: "Coat Rack - Medium",
    dimensions: 5,
    weight: 35,
    costPer: 40,
    icon: "Checkroom",
  },
  {
    Item: "Coat Rack - Small",
    dimensions: 2,
    weight: 14,
    costPer: 20,
    icon: "Checkroom",
  },
  {
    Item: "Coat Stand",
    dimensions: 12,
    weight: 84,
    costPer: 100,
    icon: "Checkroom",
  },
  {
    Item: "Coffee Maker",
    dimensions: 2,
    weight: 14,
    costPer: 18,
    icon: "Coffee",
  },
  {
    Item: "Coffee Table 4' x 2'",
    dimensions: 12,
    weight: 84,
    costPer: 95,
    icon: "TableBar",
  },
  {
    Item: "Coffee Table 3' x 2'",
    dimensions: 10,
    weight: 70,
    costPer: 80,
    icon: "TableBar",
  },
  {
    Item: "Coffee Table 5' x 3'",
    dimensions: 15,
    weight: 105,
    costPer: 110,
    icon: "TableBar",
  },
  {
    Item: "Computer Large",
    dimensions: 5,
    weight: 35,
    costPer: 50,
    icon: "Computer",
  },
  {
    Item: "Computer Medium",
    dimensions: 4,
    weight: 28,
    costPer: 35,
    icon: "Computer",
  },
  {
    Item: "Computer Small",
    dimensions: 3,
    weight: 21,
    costPer: 30,
    icon: "Computer",
  },
  {
    Item: "Computer Monitor - Flat Screen",
    dimensions: 2,
    weight: 14,
    costPer: 25,
    icon: "Monitor",
  },
  {
    Item: "Computer Monitor - Tube",
    dimensions: 4,
    weight: 28,
    costPer: 40,
    icon: "Tv",
  },
  {
    Item: "Conference Chair",
    dimensions: 15,
    weight: 105,
    costPer: 115,
    icon: "Chair",
  },
  {
    Item: "Conference Table 12' Long",
    dimensions: 45,
    weight: 315,
    costPer: 350,
    icon: "TableBar",
  },
  {
    Item: "Conference Table 8' Long",
    dimensions: 35,
    weight: 245,
    costPer: 280,
    icon: "TableBar",
  },
  {
    Item: "Conference Table 6' Long",
    dimensions: 30,
    weight: 210,
    costPer: 250,
    icon: "TableBar",
  },
  {
    Item: "Console Table",
    dimensions: 15,
    weight: 105,
    costPer: 120,
    icon: "TableBar",
  },
  { Item: "Cooler", dimensions: 3, weight: 21, costPer: 30, icon: "AcUnit" },
  {
    Item: "Corner Cabinet",
    dimensions: 20,
    weight: 140,
    costPer: 160,
    icon: "Kitchen",
  },
  {
    Item: "Credenza 9' Long",
    dimensions: 40,
    weight: 280,
    costPer: 320,
    icon: "Countertops",
  },
  {
    Item: "Credenza 7' Long",
    dimensions: 35,
    weight: 245,
    costPer: 280,
    icon: "Countertops",
  },
  {
    Item: "Credenza 5' Long",
    dimensions: 30,
    weight: 210,
    costPer: 260,
    icon: "Countertops",
  },
  { Item: "Crib", dimensions: 15, weight: 105, costPer: 125, icon: "Crib" },
  {
    Item: "Crock Pot",
    dimensions: 2,
    weight: 14,
    costPer: 20,
    icon: "SoupKitchen",
  },
  { Item: "Cubby 3'", dimensions: 3, weight: 21, costPer: 28, icon: "Apps" },
  { Item: "Cubby 9'", dimensions: 9, weight: 63, costPer: 75, icon: "Apps" },
  { Item: "Cubby 12'", dimensions: 12, weight: 84, costPer: 90, icon: "Apps" },
  { Item: "Cubicles", dimensions: 10, weight: 70, costPer: 85, icon: "GridOn" },
  { Item: "Day Bed", dimensions: 50, weight: 350, costPer: 400, icon: "Bed" },
  {
    Item: "Desk With Hutch",
    dimensions: 43,
    weight: 301,
    costPer: 350,
    icon: "Desk",
  },
  {
    Item: "Desk - Small",
    dimensions: 15,
    weight: 105,
    costPer: 120,
    icon: "Desk",
  },
  {
    Item: "Desk - Medium",
    dimensions: 20,
    weight: 140,
    costPer: 160,
    icon: "Desk",
  },
  {
    Item: "Desk - Large",
    dimensions: 25,
    weight: 175,
    costPer: 190,
    icon: "Desk",
  },
  {
    Item: "Desk - Executive",
    dimensions: 25,
    weight: 250,
    costPer: 280,
    icon: "Desk",
  },
  { Item: "Desk Chair", dimensions: 5, weight: 35, costPer: 45, icon: "Chair" },
  {
    Item: "Dining Chair",
    dimensions: 6,
    weight: 42,
    costPer: 50,
    icon: "Chair",
  },
  {
    Item: "Dining Table Small (Seats 4)",
    dimensions: 25,
    weight: 175,
    costPer: 200,
    icon: "TableBar",
  },
  {
    Item: "Dining Table Medium (Seats 6)",
    dimensions: 40,
    weight: 280,
    costPer: 320,
    icon: "TableBar",
  },
  {
    Item: "Dining Table Large (Seats 8)",
    dimensions: 60,
    weight: 420,
    costPer: 480,
    icon: "TableBar",
  },
  {
    Item: "Dishwasher",
    dimensions: 25,
    weight: 175,
    costPer: 200,
    icon: "Countertops",
  },
  {
    Item: "Display Case",
    dimensions: 19,
    weight: 133,
    costPer: 150,
    icon: "Kitchen",
  },
  {
    Item: "Dresser Single",
    dimensions: 30,
    weight: 210,
    costPer: 250,
    icon: "Inventory",
  },
  {
    Item: "Dresser Double",
    dimensions: 40,
    weight: 280,
    costPer: 320,
    icon: "Inventory",
  },
  {
    Item: "Dresser Triple",
    dimensions: 50,
    weight: 350,
    costPer: 380,
    icon: "Inventory",
  },
  {
    Item: "Drum Set",
    dimensions: 25,
    weight: 160,
    costPer: 200,
    icon: "MusicNote",
  },
  {
    Item: "Drums",
    dimensions: 20,
    weight: 140,
    costPer: 170,
    icon: "MusicNote",
  },
  {
    Item: "Dryer",
    dimensions: 25,
    weight: 175,
    costPer: 210,
    icon: "LocalLaundryService",
  },
  {
    Item: "Dumbbells (up to 30 lbs)",
    dimensions: 1,
    weight: 30,
    costPer: 40,
    icon: "FitnessCenter",
  },
  {
    Item: "Easel Small",
    dimensions: 5,
    weight: 35,
    costPer: 45,
    icon: "Brush",
  },
  {
    Item: "Easel Medium",
    dimensions: 8,
    weight: 56,
    costPer: 65,
    icon: "Brush",
  },
  {
    Item: "Easel Large",
    dimensions: 10,
    weight: 70,
    costPer: 80,
    icon: "Brush",
  },
  {
    Item: "Elliptical",
    dimensions: 68,
    weight: 476,
    costPer: 500,
    icon: "FitnessCenter",
  },
  {
    Item: "End Table 3' x 2'",
    dimensions: 10,
    weight: 70,
    costPer: 85,
    icon: "TableBar",
  },
  {
    Item: "End Table 2' x 2'",
    dimensions: 8,
    weight: 56,
    costPer: 75,
    icon: "TableBar",
  },
  {
    Item: "Entertainment Center 4' Long",
    dimensions: 60,
    weight: 420,
    costPer: 450,
    icon: "Theaters",
  },
  {
    Item: "Entertainment Center 5' Long",
    dimensions: 80,
    weight: 560,
    costPer: 600,
    icon: "Theaters",
  },
  {
    Item: "Entertainment Center 6' Long",
    dimensions: 120,
    weight: 840,
    costPer: 900,
    icon: "Theaters",
  },
  {
    Item: "Executive Chair",
    dimensions: 10,
    weight: 70,
    costPer: 85,
    icon: "Chair",
  },
  {
    Item: "Exercise Bike",
    dimensions: 48,
    weight: 336,
    costPer: 370,
    icon: "FitnessCenter",
  },
  {
    Item: "Exercise Machine",
    dimensions: 25,
    weight: 175,
    costPer: 210,
    icon: "FitnessCenter",
  },
  {
    Item: "Extra-Wide Refrigerator",
    dimensions: 65,
    weight: 455,
    costPer: 500,
    icon: "Kitchen",
  },
  {
    Item: "Fan Standing",
    dimensions: 12,
    weight: 84,
    costPer: 100,
    icon: "AcUnit",
  },
  { Item: "Fan Table", dimensions: 3, weight: 21, costPer: 30, icon: "AcUnit" },
  { Item: "Fan", dimensions: 5, weight: 35, costPer: 45, icon: "AcUnit" },
  {
    Item: "Fax Machine",
    dimensions: 2,
    weight: 14,
    costPer: 20,
    icon: "Print",
  },
  {
    Item: "File Cabinet - 2 Drawer Vertical",
    dimensions: 5,
    weight: 35,
    costPer: 50,
    icon: "Folder",
  },
  {
    Item: "File Cabinet - 4 Drawer Vertical",
    dimensions: 10,
    weight: 70,
    costPer: 100,
    icon: "Folder",
  },
  {
    Item: "Fireplace Equipment",
    dimensions: 5,
    weight: 35,
    costPer: 50,
    icon: "Fireplace",
  },
  {
    Item: `Flat Panel TV (32 to 45")`,
    dimensions: 15,
    weight: 105,
    costPer: 140,
    icon: "Tv",
  },
  {
    Item: `Flat Panel TV (46-55")`,
    dimensions: 20,
    weight: 140,
    costPer: 180,
    icon: "Tv",
  },
  {
    Item: `Flat Panel TV (over 55")`,
    dimensions: 25,
    weight: 175,
    costPer: 220,
    icon: "Tv",
  },
  {
    Item: "Floor Lamp (less than 5' Tall)",
    dimensions: 5,
    weight: 35,
    costPer: 50,
    icon: "Highlight",
  },
  {
    Item: "Floor Lamp (7' Tall)",
    dimensions: 10,
    weight: 70,
    costPer: 85,
    icon: "Highlight",
  },
  {
    Item: "Folding Chair",
    dimensions: 2,
    weight: 14,
    costPer: 25,
    icon: "EventSeat",
  },
  {
    Item: "Folding Table",
    dimensions: 8,
    weight: 56,
    costPer: 75,
    icon: "TableRestaurant",
  },
  {
    Item: "Foosball Table",
    dimensions: 30,
    weight: 210,
    costPer: 260,
    icon: "SportsEsports",
  },
  {
    Item: "Freezer 10 cuft or less",
    dimensions: 30,
    weight: 210,
    costPer: 280,
    icon: "Kitchen",
  },
  {
    Item: "Freezer 11 to 15 cuft",
    dimensions: 45,
    weight: 315,
    costPer: 360,
    icon: "Kitchen",
  },
  {
    Item: "Freezer 16+ cuft",
    dimensions: 60,
    weight: 420,
    costPer: 500,
    icon: "Kitchen",
  },
  {
    Item: "Futon (with mattress/pad)",
    dimensions: 10,
    weight: 70,
    costPer: 90,
    icon: "Bed",
  },
  {
    Item: "Futon and Mattress Queen",
    dimensions: 50,
    weight: 350,
    costPer: 400,
    icon: "Bed",
  },
  {
    Item: "Futon and Mattress King",
    dimensions: 60,
    weight: 420,
    costPer: 480,
    icon: "Bed",
  },
  {
    Item: "Game Table",
    dimensions: 15,
    weight: 105,
    costPer: 120,
    icon: "Casino",
  },
  {
    Item: "Garbage Can",
    dimensions: 5,
    weight: 35,
    costPer: 50,
    icon: "Delete",
  },
  {
    Item: "Glass Dining Table Large (Seats 8)",
    dimensions: 60,
    weight: 420,
    costPer: 480,
    icon: "TableBar",
  },
  {
    Item: "Glass Entertainment Center Large (6' or longer)",
    dimensions: 120,
    weight: 840,
    costPer: 900,
    icon: "Theaters",
  },
  {
    Item: "Glass Side Table Large (3' x 2')",
    dimensions: 20,
    weight: 140,
    costPer: 160,
    icon: "TableBar",
  },
  {
    Item: "Glider Chair",
    dimensions: 15,
    weight: 105,
    costPer: 130,
    icon: "Chair",
  },
  {
    Item: "Grand Piano",
    dimensions: 90,
    weight: 630,
    costPer: 700,
    icon: "Piano",
  },
  {
    Item: "Grandfather Clock Large",
    dimensions: 43,
    weight: 301,
    costPer: 350,
    icon: "AccessTime",
  },
  {
    Item: "Grill Large (5')",
    dimensions: 15,
    weight: 105,
    costPer: 120,
    icon: "OutdoorGrill",
  },
  { Item: "Guitar", dimensions: 5, weight: 35, costPer: 45, icon: "MusicNote" },
  {
    Item: "Gun Safe",
    dimensions: 20,
    weight: 140,
    costPer: 180,
    icon: "Security",
  },

  {
    Item: "Headboard King",
    dimensions: 11,
    weight: 65,
    costPer: 85,
    icon: "Bed",
  },
  {
    Item: "High Chair Large",
    dimensions: 8,
    weight: 56,
    costPer: 70,
    icon: "ChildCare",
  },
  {
    Item: "Humidifier / Dehumidifier",
    dimensions: 10,
    weight: 70,
    costPer: 90,
    icon: "AcUnit",
  },
  {
    Item: "Ironing Board",
    dimensions: 3,
    weight: 21,
    costPer: 35,
    icon: "Iron",
  },
  {
    Item: "Kitchen Cabinet Large",
    dimensions: 30,
    weight: 210,
    costPer: 250,
    icon: "Kitchen",
  },
  {
    Item: "Kitchen Chair",
    dimensions: 5,
    weight: 35,
    costPer: 50,
    icon: "Chair",
  },
  {
    Item: "Kitchen Stool",
    dimensions: 3,
    weight: 21,
    costPer: 35,
    icon: "Chair",
  },
  {
    Item: "Kitchen Table",
    dimensions: 20,
    weight: 140,
    costPer: 180,
    icon: "TableBar",
  },
  {
    Item: "Ladder Small",
    dimensions: 5,
    weight: 35,
    costPer: 50,
    icon: "Build",
  },
  {
    Item: "Ladder Medium",
    dimensions: 10,
    weight: 70,
    costPer: 90,
    icon: "Build",
  },
  {
    Item: "Ladder Large",
    dimensions: 150,
    weight: 105,
    costPer: 170,
    icon: "Build",
  },
  {
    Item: "Laminating Machine",
    dimensions: 1,
    weight: 7,
    costPer: 15,
    icon: "Print",
  },
  {
    Item: "Lamp - Floor or Pole",
    dimensions: 3,
    weight: 21,
    costPer: 40,
    icon: "Highlight",
  },
  {
    Item: "Office Copier/Printer",
    dimensions: 8,
    weight: 56,
    costPer: 80,
    icon: "Print",
  },
  {
    Item: "Lawn Mower",
    dimensions: 15,
    weight: 105,
    costPer: 140,
    icon: "Grass",
  },
  {
    Item: "Leaf Blower",
    dimensions: 5,
    weight: 35,
    costPer: 60,
    icon: "Grass",
  },
  {
    Item: "Legal File Box (Banker Box)",
    dimensions: 2,
    weight: 14,
    costPer: 30,
    icon: "Folder",
  },
  {
    Item: "Lingerie Chest",
    dimensions: 10,
    weight: 70,
    costPer: 90,
    icon: "Inventory",
  },
  {
    Item: "Magazine Rack",
    dimensions: 2,
    weight: 14,
    costPer: 25,
    icon: "MenuBook",
  },
  {
    Item: "Makeup Table / Vanity Bench",
    dimensions: 40,
    weight: 280,
    costPer: 320,
    icon: "TableBar",
  },
  {
    Item: "Mannequin",
    dimensions: 20,
    weight: 140,
    costPer: 180,
    icon: "Accessibility",
  },
  {
    Item: "Mattress Single/ Twin",
    dimensions: 20,
    weight: 140,
    costPer: 170,
    icon: "Bed",
  },
  {
    Item: "Mattress Full",
    dimensions: 25,
    weight: 175,
    costPer: 210,
    icon: "Bed",
  },
  {
    Item: "Mattress Queen",
    dimensions: 30,
    weight: 210,
    costPer: 250,
    icon: "Bed",
  },
  {
    Item: "Mattress King",
    dimensions: 35,
    weight: 245,
    costPer: 300,
    icon: "Bed",
  },
  {
    Item: "Mattress & Box Spring (Single/ Twin)",
    dimensions: 40,
    weight: 280,
    costPer: 350,
    icon: "Bed",
  },
  {
    Item: "Mattress & Box Spring (Full)",
    dimensions: 50,
    weight: 350,
    costPer: 420,
    icon: "Bed",
  },
  {
    Item: "Mattress & Box Spring (Queen)",
    dimensions: 60,
    weight: 420,
    costPer: 500,
    icon: "Bed",
  },
  {
    Item: "Mattress & Box Spring (King)",
    dimensions: 70,
    weight: 490,
    costPer: 580,
    icon: "Bed",
  },
  {
    Item: "Metal Locker",
    dimensions: 59,
    weight: 413,
    costPer: 480,
    icon: "Lock",
  },
  {
    Item: "Microwave",
    dimensions: 10,
    weight: 70,
    costPer: 85,
    icon: "Microwave",
  },
  {
    Item: "Microwave Cart",
    dimensions: 10,
    weight: 70,
    costPer: 90,
    icon: "Kitchen",
  },
  {
    Item: "Milk Crate",
    dimensions: 2,
    weight: 14,
    costPer: 20,
    icon: "Inventory",
  },
  {
    Item: "Mini-Refrigerator (Mini Fridge)",
    dimensions: 15,
    weight: 105,
    costPer: 130,
    icon: "Kitchen",
  },
  {
    Item: "Mirror Small (2' x 3')",
    dimensions: 5,
    weight: 35,
    costPer: 45,
    icon: "ContentCut",
  },
  {
    Item: "Mirror Medium (2.5' x 5')",
    dimensions: 8,
    weight: 56,
    costPer: 65,
    icon: "ContentCut",
  },
  {
    Item: "Mirror Large (4' x 8')",
    dimensions: 10,
    weight: 70,
    costPer: 90,
    icon: "ContentCut",
  },
  {
    Item: "Monitor Large",
    dimensions: 6,
    weight: 42,
    costPer: 55,
    icon: "Monitor",
  },
  {
    Item: "Monitor Medium",
    dimensions: 5,
    weight: 35,
    costPer: 45,
    icon: "Monitor",
  },
  {
    Item: "Monitor Small",
    dimensions: 4,
    weight: 28,
    costPer: 35,
    icon: "Monitor",
  },
  {
    Item: "Mop",
    dimensions: 3,
    weight: 21,
    costPer: 30,
    icon: "CleaningServices",
  },
  {
    Item: "Murphy Bed",
    dimensions: 12,
    weight: 840,
    costPer: 900,
    icon: "Bed",
  },
  {
    Item: "Musical Instrument Large",
    dimensions: 7,
    weight: 49,
    costPer: 80,
    icon: "MusicNote",
  },
  {
    Item: "Musical Instrument Small",
    dimensions: 3,
    weight: 21,
    costPer: 40,
    icon: "MusicNote",
  },
  {
    Item: "Nesting Table",
    dimensions: 10,
    weight: 70,
    costPer: 100,
    icon: "TableBar",
  },
  {
    Item: "Night Table",
    dimensions: 5,
    weight: 35,
    costPer: 50,
    icon: "TableBar",
  },
  {
    Item: "Accent Chair",
    dimensions: 15,
    weight: 105,
    costPer: 130,
    icon: "Chair",
  },
  {
    Item: "Ottoman Large",
    dimensions: 15,
    weight: 105,
    costPer: 140,
    icon: "Weekend",
  },
  {
    Item: "Ottoman Medium",
    dimensions: 10,
    weight: 70,
    costPer: 100,
    icon: "Weekend",
  },
  {
    Item: "Ottoman Small",
    dimensions: 3,
    weight: 35,
    costPer: 50,
    icon: "Weekend",
  },
  {
    Item: "Outdoor Chair",
    dimensions: 10,
    weight: 70,
    costPer: 85,
    icon: "Deck",
  },
  {
    Item: "Outdoor Children's Slide",
    dimensions: 10,
    weight: 70,
    costPer: 90,
    icon: "Toys",
  },
  {
    Item: "Outdoor Children's Jungle Gym",
    dimensions: 20,
    weight: 140,
    costPer: 200,
    icon: "Toys",
  },
  {
    Item: "Outdoor End Table Small",
    dimensions: 5,
    weight: 35,
    costPer: 50,
    icon: "TableBar",
  },
  {
    Item: "Outdoor End Table Medium",
    dimensions: 8,
    weight: 56,
    costPer: 70,
    icon: "TableBar",
  },
  {
    Item: "Outdoor End Table Large",
    dimensions: 10,
    weight: 70,
    costPer: 90,
    icon: "TableBar",
  },
];
